services:
  - type: web
    name: hms-backend
    env: node
    rootDir: Hospital-Management/Backend
    buildCommand: "npm install"
    startCommand: "npm start"
    autoDeploy: true
    plan: free


